import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#faf9f8',
  },
  topHeader: {
    backgroundColor: '#0078d4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    height: 56,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuButton: {
    padding: 8,
    marginRight: 12,
  },
  menuIcon: {
    color: 'white',
    fontSize: 18,
  },
  appTitle: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchButton: {
    padding: 8,
    marginRight: 8,
  },
  searchIcon: {
    color: 'white',
    fontSize: 16,
  },
  profileButton: {
    width: 32,
    height: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileIcon: {
    color: 'white',
    fontSize: 16,
  },
  mainContainer: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 280,
    backgroundColor: '#f3f2f1',
    borderRightWidth: 1,
    borderRightColor: '#e1e5e9',
  },
  sidebarItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginHorizontal: 8,
    borderRadius: 4,
  },
  sidebarItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  sidebarIcon: {
    width: 20,
    height: 20,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  sidebarIconText: {
    fontSize: 10,
    color: 'white',
  },
  sidebarItemText: {
    fontSize: 14,
    color: '#323130',
    flex: 1,
  },
  sidebarCount: {
    fontSize: 12,
    color: '#605e5c',
    backgroundColor: '#e1e5e9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    minWidth: 20,
    textAlign: 'center',
  },
  listsSection: {
    marginTop: 24,
    paddingHorizontal: 8,
  },
  listsSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 8,
  },
  listsSectionTitle: {
    fontSize: 12,
    color: '#605e5c',
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  addListButton: {
    fontSize: 16,
    color: '#0078d4',
    fontWeight: 'bold',
  },
  customList: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 4,
  },
  mainContent: {
    flex: 1,
    backgroundColor: 'white',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f2f1',
  },
  listTitleSection: {
    flex: 1,
  },
  listTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#323130',
    marginBottom: 4,
  },
  listDate: {
    fontSize: 14,
    color: '#605e5c',
  },
  moreOptionsButton: {
    padding: 8,
  },
  moreOptionsIcon: {
    fontSize: 20,
    color: '#605e5c',
  },
  suggestionsBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff4ce',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f2f1',
  },
  suggestionsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  suggestionsIcon: {
    fontSize: 16,
    marginRight: 12,
  },
  suggestionsText: {
    fontSize: 14,
    color: '#323130',
    flex: 1,
  },
  suggestionsClose: {
    fontSize: 20,
    color: '#605e5c',
    padding: 4,
  },
  addTaskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f2f1',
  },
  addTaskButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#0078d4',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  addTaskIcon: {
    fontSize: 12,
    color: '#0078d4',
    fontWeight: 'bold',
  },
  addTaskInput: {
    flex: 1,
    fontSize: 16,
    color: '#323130',
    paddingVertical: 0,
  },
  tasksContainer: {
    flex: 1,
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f8f9fa',
  },
  taskCheckbox: {
    marginRight: 16,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#0078d4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxCompleted: {
    backgroundColor: '#0078d4',
  },
  checkmark: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  taskContent: {
    flex: 1,
  },
  taskText: {
    fontSize: 16,
    color: '#323130',
    lineHeight: 22,
  },
  taskTextCompleted: {
    textDecorationLine: 'line-through',
    color: '#8a8886',
  },
  starButton: {
    padding: 8,
  },
  star: {
    fontSize: 16,
    color: '#c8c6c4',
  },
  starImportant: {
    color: '#d83b01',
  },
  completedSection: {
    marginTop: 24,
  },
  completedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#f8f9fa',
  },
  completedTitle: {
    fontSize: 14,
    color: '#605e5c',
    fontWeight: '600',
  },
  completedToggle: {
    fontSize: 16,
    color: '#605e5c',
  },
  rightPanel: {
    width: 320,
    backgroundColor: '#faf9f8',
    borderLeftWidth: 1,
    borderLeftColor: '#e1e5e9',
  },
  taskDetailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e5e9',
  },
  taskDetailTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#323130',
    flex: 1,
  },
  closeDetailPanel: {
    fontSize: 20,
    color: '#605e5c',
    padding: 4,
  },
  taskDetailContent: {
    paddingTop: 16,
  },
  detailOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  detailIcon: {
    fontSize: 16,
    marginRight: 16,
    width: 20,
  },
  detailText: {
    fontSize: 14,
    color: '#323130',
  },
  taskDetailFooter: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
  },
  createdDate: {
    fontSize: 12,
    color: '#8a8886',
  },
});